### ISSUE TITLE
Unable to start system-probe

### ISSUE THREAD

**Issue by jboyens** [DataDog/datadog-agent-boshrelease#100]
Hoping to be able to do some network performance monitoring using the Agent, but my basic attempts at getting the system-probe started haven't been successful.

Is there a plan to support this in a future release? Or are there perhaps some tips to getting it up and running using the bosh-release?

**Comment by gzussa** [comment]
Hi @jboyens Thanks for raising this to our attention.

We actually have to do some research to answer your questions. It should be included since [agent 6.14](https://github.com/DataDog/datadog-agent-boshrelease/releases/tag/2.12.6140). 
However activating it may not be straight forward indeed. We will take a look. Unfortunately, i can't provide an ETA at the moment. 

However since, you started to work on it. We would love to get details about what you tried so far. If you are willing to help us craft a PR that would be great. It seems to me that we would need to create a config template file similar to [datadog.yaml](https://github.com/DataDog/datadog-agent-boshrelease/tree/master/jobs/dd-agent/templates/config) and have scripts ( eg: [monit](https://github.com/DataDog/datadog-agent-boshrelease/blob/master/jobs/dd-agent/monit) ) use it to enable system-probe correctly.
